local o = vim.opt
o.number = true
o.mouse = 'a'
o.ignorecase = true
o.smartcase = true
o.hlsearch = true
o.wrap = true
o.breakindent = true
o.tabstop = 2
o.shiftwidth = 2
o.smartindent = true
o.autoindent = true
o.signcolumn = 'auto'
o.termguicolors = true
o.cmdheight = 0
o.cursorline = true

local g = vim.g
g.netrw_banner = 0
g.netrw_liststyle = 3
g.netrw_winsize = 20
